{{- range $name, $clientId := .Values.global.workloadIdentityClientIds }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name | kebabcase }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    azure.workload.identity/use: "true"
    {{- include "content-factory.labels" $ | nindent 4 }}
  {{- if $clientId }}
  annotations:
    azure.workload.identity/client-id: {{ $clientId | quote }}
  {{- end }}
{{- end }}

